name: simple-tests

on: push

jobs:
    test:
        name: test
        runs-on: ubuntu-latest # for underlying VM, not for container
        steps:
            - run: dotnet --version
            - run: dotnet restore
            - run: dotnet test .\MyTests\MyTests.csproj