name: simple-tests

on: push

permissions:
  contents: read
  actions: read
  checks: write

jobs:
    test:
        name: test
        runs-on: ubuntu-latest # for underlying VM, not for container
        container: 
          image: prusovak2/lanatra-test-envs:ubuntu-java20
          options: --user 1001
        steps:
            - uses: actions/checkout@v3         # checkout the repo
            - run: ls
            - run: dotnet --version
            - run: java --version
            - run: echo $JAVA_HOME
            - run: dotnet restore ./GithubActionsPoc/GithubActionsPoc.sln
            - run: dotnet test ./MyTests/MyTests.csproj --logger "trx;LogFileName=test-results.trx"
            
            - name: Test Report
              uses: dorny/test-reporter@v1
              if: success() || failure()    # run this step even if previous step failed
              with:
                  name: MyAwesomeTests            # Name of the check run which will be created
                  path: ./MyTests/TestResults/*.trx    # Path to test results
                  reporter: dotnet-trx        # Format of test results